export enum UKRAINE_REGIONS {
    Crimea = 1000,
    CherkasyOblast,
    ChernihivOblast,
    ChernivtsiOblast,
    DnipropetrovskOblast,
    DonetskOblast,
    IvanoFrankivskOblast,
    KharkivOblast,
    KhersonOblast,
    KhmelnytskOblast,
    KirovohradOblast,
    KyivOblast,
    LuhanskOblast,
    LvivOblast,
    MykolaivOblast,
    OdesaOblast,
    PoltavaOblast,
    RivneOblast,
    SumyOblast,
    TernopilOblast,
    VinnytsiaOblast,
    VolynOblast,
    ZakarpattiaOblast,
    ZaporizhzhiaOblast,
    ZhytomyrOblast,
    Kyiv,
    Sevastopol
}


export const UKRAINE_REGIONS_DISPLAY = {
    [UKRAINE_REGIONS.Crimea]: 'Автономна Республіка Крим',
    [UKRAINE_REGIONS.CherkasyOblast]: 'Черкаська область',
    [UKRAINE_REGIONS.ChernihivOblast]: 'Чернігівська область',
    [UKRAINE_REGIONS.ChernivtsiOblast]: 'Чернівецька область',
    [UKRAINE_REGIONS.DnipropetrovskOblast]: 'Дніпропетровська область',
    [UKRAINE_REGIONS.DonetskOblast]: 'Донецька область',
    [UKRAINE_REGIONS.IvanoFrankivskOblast]: 'Івано-Франківська область',
    [UKRAINE_REGIONS.KharkivOblast]: 'Харківська область',
    [UKRAINE_REGIONS.KhersonOblast]: 'Херсонська область',
    [UKRAINE_REGIONS.KhmelnytskOblast]: 'Хмельницька область',
    [UKRAINE_REGIONS.KirovohradOblast]: 'Кіровоградська область',
    [UKRAINE_REGIONS.KyivOblast]: 'Київська область',
    [UKRAINE_REGIONS.LuhanskOblast]: 'Луганська область',
    [UKRAINE_REGIONS.LvivOblast]: 'Львівська область',
    [UKRAINE_REGIONS.MykolaivOblast]: 'Миколаївська область',
    [UKRAINE_REGIONS.OdesaOblast]: 'Одеська область',
    [UKRAINE_REGIONS.PoltavaOblast]: 'Полтавська область',
    [UKRAINE_REGIONS.RivneOblast]: 'Рівненська область',
    [UKRAINE_REGIONS.SumyOblast]: 'Сумська область',
    [UKRAINE_REGIONS.TernopilOblast]: 'Тернопільська область',
    [UKRAINE_REGIONS.VinnytsiaOblast]: 'Вінницька область',
    [UKRAINE_REGIONS.VolynOblast]: 'Волинська область',
    [UKRAINE_REGIONS.ZakarpattiaOblast]: 'Закарпатська область',
    [UKRAINE_REGIONS.ZaporizhzhiaOblast]: 'Запорізька область',
    [UKRAINE_REGIONS.ZhytomyrOblast]: 'Житомирська область',
    [UKRAINE_REGIONS.Kyiv]: 'Київ',
    [UKRAINE_REGIONS.Sevastopol]: 'Севастополь'
};
